/*
 * Enhanced Post Processing Tool (EPPT) Copyright (c) 2019.
 *
 * EPPT is copyrighted by the State of California, Department of Water Resources. It is licensed
 * under the GNU General Public License, version 2. This means it can be
 * copied, distributed, and modified freely, but you may not restrict others
 * in their ability to copy, distribute, and modify it. See the license below
 * for more details.
 *
 * GNU General Public License
 */

package gov.ca.water.quickresults.ui.projectconfig.scenarioconfig;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;
import java.util.Set;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

import gov.ca.water.calgui.bo.GUILinksAllModelsBO;
import gov.ca.water.calgui.bo.SimpleFileFilter;
import gov.ca.water.calgui.constant.Constant;
import gov.ca.water.calgui.constant.EpptPreferences;
import gov.ca.water.calgui.project.EpptDssContainer;
import gov.ca.water.calgui.project.EpptScenarioRun;

import rma.swing.RmaJComboBox;
import rma.swing.RmaJDescriptionField;
import rma.swing.RmaJTable;
import rma.swing.table.RmaCellEditor;

/**
 * Company: Resource Management Associates
 *
 * @author <a href="mailto:adam@rmanet.com">Adam Korynta</a>
 * @since 05-29-2019
 */
public class ScenarioEditorPanel
{
	private final ScenarioDssTableModel _scenarioDssTableModel;
	private JPanel _panel1;
	private JTable _dssTable;
	private JButton _addButton;
	private JButton _removeButton;
	private JButton _upButton;
	private JButton _downButton;
	private JTextField _nameField;
	private JTextField _descriptionField;
	private JTextField _outputTextField;
	private JTextField _wreslTextField;
	private JButton _wreslButton;
	private JComboBox<GUILinksAllModelsBO.Model> _modelCombobox;
	private JButton _outputPathButton;
	private JTextField _waterYearTable;
	private JButton _wyTableBtn;
	private static JFileChooser fileChooser;

	ScenarioEditorPanel(LoadingDss loadingDss)
	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
		_scenarioDssTableModel = new ScenarioDssTableModel(loadingDss);
		_dssTable.setModel(_scenarioDssTableModel);
		initModelCombo();
		_addButton.addActionListener(this::addExtraDss);
		_removeButton.addActionListener(this::removeExtraDss);
		_outputPathButton.addActionListener(this::selectOutputPath);
		_wreslButton.addActionListener(this::selectWreslMain);
		_dssTable.getColumnModel().getColumn(ScenarioDssTableModel.DSS_PATH_COLUMN).setCellEditor(new FileChooserEditor());
		_dssTable.getColumnModel().getColumn(ScenarioDssTableModel.DSS_PATH_COLUMN).setCellRenderer(new FileChooserRenderer());
		_dssTable.getColumnModel().getColumn(ScenarioDssTableModel.A_PART_COLUMN).setCellEditor(new ComboBoxCellEditor(new RmaJComboBox()));
		_dssTable.getColumnModel().getColumn(ScenarioDssTableModel.F_PART_COLUMN).setCellEditor(new ComboBoxCellEditor(new RmaJComboBox()));
		_nameField.requestFocus();
		String time = Long.toString(new Date().getTime()).substring(6);
		_nameField.setText("NewScenarioRun " + time);
		_nameField.selectAll();
		_waterYearTable.setText(Paths.get(Constant.WY_TYPES_TABLE).normalize().toString());
		_wyTableBtn.addActionListener(e -> chooseWaterYearTable());
		_wreslTextField.setText(Constant.WRESL_MAIN);
	}

	private void chooseWaterYearTable()
	{
		JFileChooser jFileChooser = new JFileChooser();
		jFileChooser.setCurrentDirectory(Paths.get(_waterYearTable.getText()).toFile());
		jFileChooser.setFileFilter(new SimpleFileFilter("TABLE"));
		jFileChooser.setDialogTitle("Choose Water Year Table File");
		jFileChooser.showOpenDialog(SwingUtilities.windowForComponent($$$getRootComponent$$$()));
		File selectedFile = jFileChooser.getSelectedFile();
		if(selectedFile != null)
		{
			_waterYearTable.setText(selectedFile.toString());
		}
	}

	private void removeExtraDss(ActionEvent actionEvent)
	{
		int selectedRow = _dssTable.getSelectedRow();
		if(selectedRow >= 0 && _scenarioDssTableModel.getRowType(selectedRow) == ScenarioDssTableModel.RowType.EXTRA)
		{
			_scenarioDssTableModel.removeExtraDss(selectedRow);
		}
	}

	private JFileChooser getFileChooser(String s)
	{
		if(fileChooser == null)
		{
			fileChooser = new JFileChooser(s);
			fileChooser.setCurrentDirectory(EpptPreferences.getLastProjectConfiguration().getParent().toFile());
		}
		return fileChooser;
	}

	private void initModelCombo()
	{
		for(GUILinksAllModelsBO.Model model : GUILinksAllModelsBO.Model.values())
		{
			_modelCombobox.addItem(model);
		}
		_modelCombobox.setSelectedItem(GUILinksAllModelsBO.Model.values().get(0));
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		createUIComponents();
		_panel1 = new JPanel();
		_panel1.setLayout(new BorderLayout(0, 0));
		_panel1.setPreferredSize(new Dimension(700, 500));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		_panel1.add(panel1, BorderLayout.CENTER);
		panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Required Files"));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
		panel1.add(panel2, BorderLayout.SOUTH);
		_addButton = new JButton();
		_addButton.setPreferredSize(new Dimension(45, 24));
		_addButton.setText("+");
		panel2.add(_addButton);
		_removeButton = new JButton();
		_removeButton.setPreferredSize(new Dimension(45, 24));
		_removeButton.setText("-");
		panel2.add(_removeButton);
		_upButton.setPreferredSize(new Dimension(45, 24));
		panel2.add(_upButton);
		_downButton.setPreferredSize(new Dimension(45, 24));
		panel2.add(_downButton);
		final JScrollPane scrollPane1 = new JScrollPane();
		panel1.add(scrollPane1, BorderLayout.CENTER);
		scrollPane1.setViewportView(_dssTable);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new BorderLayout(0, 0));
		_panel1.add(panel3, BorderLayout.NORTH);
		panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "General Description"));
		final JPanel panel4 = new JPanel();
		panel4.setLayout(new GridBagLayout());
		panel3.add(panel4, BorderLayout.CENTER);
		final JLabel label1 = new JLabel();
		label1.setText("Scenario Name:");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(label1, gbc);
		_nameField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.gridwidth = 2;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(_nameField, gbc);
		final JLabel label2 = new JLabel();
		label2.setText("Description:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(label2, gbc);
		final JLabel label3 = new JLabel();
		label3.setText("Model:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(label3, gbc);
		_descriptionField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.gridwidth = 2;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(_descriptionField, gbc);
		final JLabel label4 = new JLabel();
		label4.setText("Study Main Directory:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(label4, gbc);
		_outputTextField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 3;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(_outputTextField, gbc);
		_modelCombobox = new JComboBox();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.gridwidth = 2;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(_modelCombobox, gbc);
		_outputPathButton = new JButton();
		_outputPathButton.setPreferredSize(new Dimension(45, 24));
		_outputPathButton.setText("...");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel4.add(_outputPathButton, gbc);
		final JPanel panel5 = new JPanel();
		panel5.setLayout(new BorderLayout(0, 0));
		_panel1.add(panel5, BorderLayout.SOUTH);
		panel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "QA/QC Report"));
		final JPanel panel6 = new JPanel();
		panel6.setLayout(new GridBagLayout());
		panel5.add(panel6, BorderLayout.CENTER);
		final JLabel label5 = new JLabel();
		label5.setText("EPPT WRESL Script");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel6.add(label5, gbc);
		_wreslTextField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel6.add(_wreslTextField, gbc);
		_wreslButton = new JButton();
		_wreslButton.setPreferredSize(new Dimension(45, 24));
		_wreslButton.setText("...");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel6.add(_wreslButton, gbc);
		final JLabel label6 = new JLabel();
		label6.setText("Water Year Table File:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel6.add(label6, gbc);
		_waterYearTable = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel6.add(_waterYearTable, gbc);
		_wyTableBtn = new JButton();
		_wyTableBtn.setPreferredSize(new Dimension(45, 24));
		_wyTableBtn.setRolloverEnabled(false);
		_wyTableBtn.setText("...");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel6.add(_wyTableBtn, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return _panel1;
	}

	private void createUIComponents()
	{
		_dssTable = new RmaJTable();
		_downButton = new JButton("<html>&#9660;</html>");
		_upButton = new JButton("<html>&#9650;</html>");
	}

	private void addExtraDss(ActionEvent e)
	{
		_scenarioDssTableModel.addExtraDss();
	}

	private void selectWreslMain(ActionEvent actionEvent)
	{
		JFileChooser fileChooser = getFileChooser("Select WRESL Main");
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		fileChooser.setFileFilter(new SimpleFileFilter("WRESL"));
		fileChooser.showDialog(SwingUtilities.windowForComponent($$$getRootComponent$$$()), "Select");
		File selectedFile = fileChooser.getSelectedFile();
		if(selectedFile != null)
		{
			_wreslTextField.setText(selectedFile.toString());
		}
	}

	private void selectOutputPath(ActionEvent actionEvent)
	{
		JFileChooser fileChooser = getFileChooser("Select Scenario Run Directory");
		fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fileChooser.showDialog(SwingUtilities.windowForComponent($$$getRootComponent$$$()), "Select");
		File selectedFile = fileChooser.getSelectedFile();
		if(selectedFile != null)
		{
			_outputTextField.setText(selectedFile.toString());
		}
	}

	private void selectDss(RmaJDescriptionField textField)
	{
		JFileChooser fileChooser = getFileChooser("Select Scenario Run Directory");
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		fileChooser.setFileFilter(new SimpleFileFilter("DSS"));
		fileChooser.showDialog(SwingUtilities.windowForComponent($$$getRootComponent$$$()), "Select");
		File selectedFile = fileChooser.getSelectedFile();
		if(selectedFile != null)
		{
			String fileName = selectedFile.toString();
			if(!fileName.toLowerCase().endsWith(".dss"))
			{
				fileName += ".dss";
			}
			textField.setText(fileName);
		}
	}

	private EpptDssContainer createDssContainer(String scenarioName)
	{
		return _scenarioDssTableModel.createDssContainer(scenarioName);
	}

	boolean validateRun()
	{
		return !_nameField.getText().isEmpty();
	}

	/**
	 * @return null if canceled, builds a new Scenario Run otherwise
	 */
	EpptScenarioRun createRun()
	{
		TableCellEditor editor = _dssTable.getCellEditor();
		if(editor != null)
		{
			editor.stopCellEditing();
		}
		String name = _nameField.getText();
		String description = _descriptionField.getText();
		GUILinksAllModelsBO.Model model = (GUILinksAllModelsBO.Model) _modelCombobox.getSelectedItem();
		Path outputPath = Paths.get(_outputTextField.getText());
		Path wreslMain = Paths.get(_wreslTextField.getText());
		EpptDssContainer dssContainer = createDssContainer(name);
		Path waterYearTablePath = Paths.get(_waterYearTable.getText());
		return new EpptScenarioRun(name, description, model, outputPath, wreslMain, waterYearTablePath,
				dssContainer);
	}

	void fillPanel(EpptScenarioRun scenarioRun)
	{
		_nameField.setText(scenarioRun.getName());
		_descriptionField.setText(scenarioRun.getDescription());
		_modelCombobox.setSelectedItem(scenarioRun.getModel());
		Path outputPath = scenarioRun.getOutputPath();
		if(outputPath != null)
		{
			_outputTextField.setText(outputPath.toString());
		}
		Path wreslMain = scenarioRun.getWreslMain();
		if(wreslMain != null)
		{
			_wreslTextField.setText(wreslMain.toString());
		}
		EpptDssContainer dssContainer = scenarioRun.getDssContainer();
		_scenarioDssTableModel.fillModel(dssContainer);
		_waterYearTable.setText(scenarioRun.getWaterYearTable().toString());
	}

	void shutdown()
	{
		_scenarioDssTableModel.shutdown();
	}

	private final class FileChooserEditor extends RmaCellEditor
	{

		private RmaJDescriptionField _descriptionField = new RmaJDescriptionField()
		{
			@Override
			public void displayChooserDialog()
			{
				selectDss(_descriptionField);
				stopCellEditing();
			}
		};

		private FileChooserEditor()
		{
			super(new JTextField());
			FileChooserEditor.this.setClickCountToStart(1);
		}

		@Override
		public Object getCellEditorValue()
		{
			Object retval;
			if(_descriptionField != null)
			{
				retval = _descriptionField.getText();
			}
			else
			{
				retval = super.getCellEditorValue();
			}
			return retval;
		}

		@Override
		public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column)
		{
			if(value == null)
			{
				_descriptionField.setText("");
			}
			else
			{
				_descriptionField.setText(value.toString());
			}
			return _descriptionField;
		}
	}

	public static final class FileChooserRenderer extends RmaJDescriptionField implements TableCellRenderer
	{

		private FileChooserRenderer()
		{
			FileChooserRenderer.this.setBorder(new EmptyBorder(1, 1, 1, 1));
		}

		@Override
		public Component getTableCellRendererComponent(final JTable table,
													   Object value, boolean isSelected, boolean hasFocus, int row,
													   int column)
		{
			if(value != null)
			{
				String str = value.toString();
				setText(str);
			}
			else
			{
				setText("");
			}
			if(isSelected)
			{
				setForeground(table.getSelectionForeground());
				setBackground(table.getSelectionBackground());
			}
			else
			{
				setForeground(table.getForeground());
				setBackground(table.getBackground());
			}
			return this;
		}
	}

	private class ComboBoxCellEditor extends DefaultCellEditor implements TableCellRenderer
	{
		private final RmaJComboBox<String> _comboBox;

		private ComboBoxCellEditor(RmaJComboBox comboBox)
		{
			super(comboBox);
			comboBox.setEditable(true);
			_comboBox = comboBox;
		}

		@Override
		public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column)
		{
			Component tableCellEditorComponent = super.getTableCellEditorComponent(table, value, isSelected, row, column);
			if(tableCellEditorComponent == _comboBox)
			{
				Object selectedItem = _comboBox.getSelectedItem();
				_comboBox.removeAllItems();
				if(column == ScenarioDssTableModel.A_PART_COLUMN)
				{
					Set<String> aParts = _scenarioDssTableModel.getAPartsForRow(row);
					aParts.forEach(_comboBox::addItem);
				}
				else if(column == ScenarioDssTableModel.F_PART_COLUMN)
				{
					Set<String> fParts = _scenarioDssTableModel.getFPartsForRow(row);
					fParts.forEach(_comboBox::addItem);
				}
				_comboBox.setSelectedItem(selectedItem);
			}
			return _comboBox;
		}

		@Override
		public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
		{
			_comboBox.setSelectedItem(value);
			return _comboBox;
		}

	}
}
