/*
 * Enhanced Post Processing Tool (EPPT) Copyright (c) 2020.
 *
 * EPPT is copyrighted by the State of California, Department of Water Resources. It is licensed
 * under the GNU General Public License, version 2. This means it can be
 * copied, distributed, and modified freely, but you may not restrict others
 * in their ability to copy, distribute, and modify it. See the license below
 * for more details.
 *
 * GNU General Public License
 */

package gov.ca.water.quickresults.ui.global;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.Month;
import java.util.Arrays;
import javax.swing.*;

import gov.ca.water.calgui.bo.WaterYearPeriodRange;

class AddAnnualFilterDialog extends JDialog
{
	private JPanel _contentPane;
	private JButton _buttonOK;
	private JButton _buttonCancel;
	private JTextField _nameTextField;
	private JRadioButton _singleMonthRadioButton;
	private JRadioButton _seasonalPeriodRadioButton;
	private JComboBox _singleMonthComboBox;
	private JComboBox _seasonalPeriodStartCombobox;
	private JComboBox _seasonalPeriodEndCombobox;
	private JSpinner _startYear;
	private JSpinner _endYear;
	private JPanel _en;
	private boolean _canceled = true;

	AddAnnualFilterDialog(Frame frame)
	{
		super(frame, "New Parameter", true);
		$$$setupUI$$$();
		setContentPane(_contentPane);
		setModal(true);
		getRootPane().setDefaultButton(_buttonOK);
		_buttonOK.addActionListener(e -> onOK());
		_buttonCancel.addActionListener(e -> onCancel());
		// call onCancel() when cross is clicked
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter()
		{
			@Override
			public void windowClosing(WindowEvent e)
			{
				onCancel();
			}
		});

		// call onCancel() on ESCAPE
		_contentPane.registerKeyboardAction(e -> onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
				JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
		pack();
		setPreferredSize(new Dimension(550, 300));
		setMinimumSize(new Dimension(550, 300));
		setLocationRelativeTo(frame);
		Arrays.asList(Month.values()).forEach(_singleMonthComboBox::addItem);
		Arrays.asList(Month.values()).forEach(_seasonalPeriodStartCombobox::addItem);
		Arrays.asList(Month.values()).forEach(_seasonalPeriodEndCombobox::addItem);
		ButtonGroup buttonGroup = new ButtonGroup();
		buttonGroup.add(_seasonalPeriodRadioButton);
		buttonGroup.add(_singleMonthRadioButton);
		_singleMonthRadioButton.addActionListener(e -> radioSelectionChanged(e));
		_seasonalPeriodRadioButton.addActionListener(e -> radioSelectionChanged(e));
		_startYear.setValue(1921);
		_endYear.setValue(2003);
	}

	private void radioSelectionChanged(ActionEvent e)
	{
		_singleMonthComboBox.setEnabled(_singleMonthRadioButton.isSelected());
		_seasonalPeriodStartCombobox.setEnabled(!_singleMonthRadioButton.isSelected());
		_seasonalPeriodEndCombobox.setEnabled(!_singleMonthRadioButton.isSelected());
	}

	AddAnnualFilterDialog(Frame frame, WaterYearPeriodRange selectedItem)
	{
		this(frame);
		_nameTextField.setText(selectedItem.getWaterYearPeriod().getPeriodName());
		if(selectedItem.getStartYear().getYear() == selectedItem.getEndYear().getYear())
		{
			_singleMonthRadioButton.setSelected(true);
			_singleMonthComboBox.setSelectedItem(selectedItem.getStartYear());
		}
		else
		{
			_seasonalPeriodRadioButton.setSelected(true);
			_seasonalPeriodStartCombobox.setSelectedItem(selectedItem.getStartYear());
			_seasonalPeriodEndCombobox.setSelectedItem(selectedItem.getEndYear());
		}
	}

	public boolean isCanceled()
	{
		return _canceled;
	}

	private void onOK()
	{
		_canceled = false;
		// add your code here
		dispose();
	}

	private void onCancel()
	{
		// add your code here if necessary
		dispose();
	}

	String getPeriodName()
	{
		return _nameTextField.getText();
	}

	int getStartYear()
	{
		if(_singleMonthRadioButton.isSelected())
		{
			return (int) _singleMonthComboBox.getSelectedItem();
		}
		else
		{
			return (int) _seasonalPeriodStartCombobox.getSelectedItem();
		}
	}

	int getEndYear()
	{
		if(_singleMonthRadioButton.isSelected())
		{
			return (int) _singleMonthComboBox.getSelectedItem();
		}
		else
		{
			return (int) _seasonalPeriodEndCombobox.getSelectedItem();
		}
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		_contentPane = new JPanel();
		_contentPane.setLayout(new BorderLayout(5, 5));
		_contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 0, 5), null));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		_contentPane.add(panel1, BorderLayout.SOUTH);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new BorderLayout(0, 0));
		panel1.add(panel2, BorderLayout.WEST);
		final JLabel label1 = new JLabel();
		Font label1Font = this.$$$getFont$$$(null, Font.ITALIC, -1, label1.getFont());
		if(label1Font != null)
		{
			label1.setFont(label1Font);
		}
		label1.setText("*User Defined parameters do not persist on application close");
		panel2.add(label1, BorderLayout.CENTER);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		panel1.add(panel3, BorderLayout.EAST);
		_buttonOK = new JButton();
		_buttonOK.setMaximumSize(new Dimension(70, 25));
		_buttonOK.setMinimumSize(new Dimension(70, 25));
		_buttonOK.setPreferredSize(new Dimension(70, 25));
		_buttonOK.setText("OK");
		panel3.add(_buttonOK);
		_buttonCancel = new JButton();
		_buttonCancel.setMaximumSize(new Dimension(70, 25));
		_buttonCancel.setMinimumSize(new Dimension(70, 25));
		_buttonCancel.setPreferredSize(new Dimension(70, 25));
		_buttonCancel.setText("Cancel");
		panel3.add(_buttonCancel);
		final JPanel panel4 = new JPanel();
		panel4.setLayout(new BorderLayout(10, 10));
		_contentPane.add(panel4, BorderLayout.CENTER);
		final JPanel panel5 = new JPanel();
		panel5.setLayout(new GridBagLayout());
		panel5.setPreferredSize(new Dimension(250, 108));
		panel4.add(panel5, BorderLayout.CENTER);
		final JLabel label2 = new JLabel();
		label2.setHorizontalAlignment(2);
		label2.setHorizontalTextPosition(2);
		label2.setText("Name:");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 0.2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel5.add(label2, gbc);
		_nameTextField = new JTextField();
		_nameTextField.setEditable(true);
		_nameTextField.setEnabled(true);
		_nameTextField.setHorizontalAlignment(2);
		_nameTextField.setPreferredSize(new Dimension(400, 26));
		_nameTextField.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel5.add(_nameTextField, gbc);
		_seasonalPeriodRadioButton = new JRadioButton();
		_seasonalPeriodRadioButton.setSelected(true);
		_seasonalPeriodRadioButton.setText("Seasonal Period");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel5.add(_seasonalPeriodRadioButton, gbc);
		_en = new JPanel();
		_en.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(5, 5, 5, 5);
		panel5.add(_en, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		_en.add(spacer1, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.VERTICAL;
		_en.add(spacer2, gbc);
		_startYear = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		_en.add(_startYear, gbc);
		_endYear = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		_en.add(_endYear, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont)
	{
		if(currentFont == null)
		{
			return null;
		}
		String resultName;
		if(fontName == null)
		{
			resultName = currentFont.getName();
		}
		else
		{
			Font testFont = new Font(fontName, Font.PLAIN, 10);
			if(testFont.canDisplay('a') && testFont.canDisplay('1'))
			{
				resultName = fontName;
			}
			else
			{
				resultName = currentFont.getName();
			}
		}
		return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return _contentPane;
	}

}


