# Makefile to update the catalogs for dss files
# get all files under current directory
JAVA_FILES = TestNetwork.java MainTest.java
#
PACKAGE_LOC=calsim/gym/test
#
TEST_PACKAGE=calsim.gym.test
#
include ../../common.test.makefile
