/*
 * Copyright (c) 2019
 * California Department of Water Resources
 * All Rights Reserved.  DWR PROPRIETARY/CONFIDENTIAL.
 * Source may not be released without written approval from DWR
 */

package gov.ca.water.calgui.presentation;

import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

import calsim.app.Project;
import calsim.gui.DtsTreeModel;
import calsim.gui.DtsTreePanel;
import calsim.gui.GuiUtils;
import gov.ca.water.calgui.bo.DataTableModel;
import gov.ca.water.calgui.bo.RBListItemBO;
import gov.ca.water.calgui.bo.ResultUtilsBO;
import gov.ca.water.calgui.bus_delegate.IAllButtonsDele;
import gov.ca.water.calgui.bus_delegate.IApplyDynamicConDele;
import gov.ca.water.calgui.bus_delegate.IScenarioDele;
import gov.ca.water.calgui.bus_delegate.IVerifyControlsDele;
import gov.ca.water.calgui.bus_delegate.impl.AllButtonsDeleImp;
import gov.ca.water.calgui.bus_delegate.impl.ApplyDynamicConDeleImp;
import gov.ca.water.calgui.bus_delegate.impl.ScenarioDeleImp;
import gov.ca.water.calgui.bus_delegate.impl.VerifyControlsDeleImp;
import gov.ca.water.calgui.bus_service.IModelRunSvc;
import gov.ca.water.calgui.bus_service.IScenarioSvc;
import gov.ca.water.calgui.bus_service.ISeedDataSvc;
import gov.ca.water.calgui.bus_service.impl.ModelRunSvcImpl;
import gov.ca.water.calgui.bus_service.impl.ScenarioSvcImpl;
import gov.ca.water.calgui.bus_service.impl.SeedDataSvcImpl;
import gov.ca.water.calgui.bus_service.impl.XMLParsingSvcImpl;
import gov.ca.water.calgui.constant.Constant;
import gov.ca.water.calgui.tech_service.IAuditSvc;
import gov.ca.water.calgui.tech_service.IDialogSvc;
import gov.ca.water.calgui.tech_service.IErrorHandlingSvc;
import gov.ca.water.calgui.tech_service.impl.AuditSvcImpl;
import gov.ca.water.calgui.tech_service.impl.DialogSvcImpl;
import gov.ca.water.calgui.tech_service.impl.ErrorHandlingSvcImpl;
import org.apache.commons.io.FilenameUtils;
import org.apache.log4j.Logger;
import org.swixml.SwingEngine;

/**
 * This class is for Listening all the action events(Button click) which are
 * generated by the application.
 *
 * @author Mohan
 */
public class GlobalActionListener implements ActionListener
{
	private static final Logger LOG = Logger.getLogger(GlobalActionListener.class.getName());
	private final SwingEngine _swingEngine = XMLParsingSvcImpl.getXMLParsingSvcImplInstance().getSwingEngine();
	private final IScenarioDele _scenarioDele = new ScenarioDeleImp();
	private final IAllButtonsDele _allButtonsDele = new AllButtonsDeleImp();
	private final IScenarioSvc _scenarioSvc = ScenarioSvcImpl.getScenarioSvcImplInstance();
	private final IAuditSvc _auditSvc = AuditSvcImpl.getAuditSvcImplInstance();
	private final IModelRunSvc _modelRunSvc = new ModelRunSvcImpl();
	private final ISeedDataSvc _seedDataSvc = SeedDataSvcImpl.getSeedDataSvcImplInstance();
	private final IDialogSvc _dialogSvc = DialogSvcImpl.getDialogSvcInstance();
	private final IVerifyControlsDele _verifyControlsDele = new VerifyControlsDeleImp();
	private final IErrorHandlingSvc _errorHandlingSvc = new ErrorHandlingSvcImpl();
	private final IApplyDynamicConDele _applyDynamicConDele = new ApplyDynamicConDeleImp();
	private JList<String> _lstReports = null;

	@SuppressWarnings("unchecked")
	@Override
	public void actionPerformed(ActionEvent ae)
	{
		try
		{
			_lstReports = (JList<String>) _swingEngine.find("lstReports");
			final JList<RBListItemBO> lstScenarios = (JList<RBListItemBO>) _swingEngine.find("SelectedList");
			JTable table = null;
			switch(ae.getActionCommand())
			{

				case "AC_Power":

					List<RBListItemBO> scendarios = new ArrayList<>();
					ListModel<RBListItemBO> model = lstScenarios.getModel();
					for(int i = 0; i < model.getSize(); i++)
					{
						scendarios.add(model.getElementAt(i));
					}
					PowerFrame pf = new PowerFrame(scendarios);
					break;

				case "AC_SaveScen":
					if(FilenameUtils.removeExtension(((JTextField) _swingEngine.find("run_txfScen")).getText())
									.toUpperCase().equals("DEFAULT") && _allButtonsDele.defaultCLSIsProtected())
					{

						_dialogSvc.getOK(
								"The CalLite GUI is not allowed to overwrite DEFAULT.CLS. Please use Save As to save to a different scenario file.",
								JOptionPane.ERROR_MESSAGE);

					}
					else
					{
						this._allButtonsDele.saveCurrentStateToFile();
					}
					break;
				case "AC_SaveScenAs":
					this._allButtonsDele.saveAsButton();
					break;
				case "AC_ViewScen":
					loadViewScen();
					break;
				case "AC_LoadScen":

					boolean doLoad = true; // Check for changed scenario prior to
					// load -
					// tad 20170202
					if(_auditSvc.hasValues())
					{
						String clsFileName = FilenameUtils
								.removeExtension(((JTextField) _swingEngine.find("run_txfScen")).getText());

						String option = _dialogSvc.getYesNoCancel("Scenario selections have changed for " + clsFileName
								+ ". Would you like to save the changes?", JOptionPane.QUESTION_MESSAGE);
						switch(option)
						{
							case "Cancel":

								doLoad = false;
								break;

							case "Yes":

								doLoad = this._allButtonsDele.saveCurrentStateToFile(clsFileName);
								break;

							case "No":

								doLoad = true;
								break;
						}
					}
					if(doLoad)
					{
						JFileChooser fChooser = new JFileChooser(Constant.SCENARIOS_DIR);
						fChooser.setMultiSelectionEnabled(false);
						FileNameExtensionFilter filter = new FileNameExtensionFilter("CLS FILES (.cls)", "cls");
						fChooser.setFileFilter(filter);
						int val = fChooser.showOpenDialog(_swingEngine.find(Constant.MAIN_FRAME_NAME));
						if(val == JFileChooser.APPROVE_OPTION
								&& this._allButtonsDele.verifyTheSelectedFiles(fChooser, Constant.CLS_EXT))
						{
							String fileName = fChooser.getSelectedFile().getName();
							loadScenarioButton(fileName);
						}
					}
					break;
				case "AC_Help":
					this._allButtonsDele.helpButton();
					break;
				case "AC_RUN":
					runSingleBatch();
					break;
				case "AC_BATCH":
					this._allButtonsDele.runMultipleBatch();
					break;
				case "AC_About":
					this._allButtonsDele.aboutButton();
					break;
				case "AC_Exit":
					this._allButtonsDele.windowClosing();
					break;
				case "AC_Select_DSS_SV":
					this._allButtonsDele.selectingSVAndInitFile("hyd_DSS_SV", "hyd_DSS_SV_F", "txf_Manual_SV",
							"txf_Manual_SV_F");
					break;
				case "AC_Select_DSS_Init":
					this._allButtonsDele.selectingSVAndInitFile("hyd_DSS_Init", "hyd_DSS_Init_F", "txf_Manual_Init",
							"txf_Manual_Init_F");
					break;
				case "Fac_TableEdit":
					TitledBorder title = null;
					if(ae.getSource() instanceof JButton)
					{
						JButton btn = (JButton) ae.getSource();
						String titlestr = btn.getText();
						title = BorderFactory.createTitledBorder(titlestr);
					}
					JPanel pan = (JPanel) _swingEngine.find("fac_pan6");
					pan.setBorder(title);
					break;
				case "Reg_Copy":
					table = (JTable) _swingEngine.find("tblRegValues");
					this._allButtonsDele.copyTableValues(table);
					break;
				case "Reg_Paste":
					table = (JTable) _swingEngine.find("tblRegValues");
					JRadioButton userDefined = (JRadioButton) _swingEngine.find("btnRegUD");
					if(userDefined.isSelected())
					{
						this._allButtonsDele.pasteTableValues(table);
					}
					else
					{
						_errorHandlingSvc.validationeErrorHandler("You can't paste untel you select user defined.",
								"You can't paste untel you select user defined.",
								(JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME));
					}
					break;
				case "Op_TableEdit":
					this._allButtonsDele.editButtonOnOperations((JComponent) ae.getSource());
					break;
				case "Op_Generate":

					runSingleBatchForWsiDi();
					break;
				case "Op_Read":
					this._allButtonsDele.readButtonInOperations();
					break;
				case "Op_Default":
					this._allButtonsDele.defaultButtonOnOperations();
					break;
				case "Op_Copy":
					table = (JTable) _swingEngine.find("tblOpValues");
					this._allButtonsDele.copyTableValues(table);
					break;
				case "Op_Paste":
					table = (JTable) _swingEngine.find("tblOpValues");
					this._allButtonsDele.pasteTableValues(table);
					break;

				// From Custom Results dashboard

				case "AC_Controls":
					ControlFrame cf = ResultUtilsBO.getResultUtilsInstance(null).getControlFrame();
					cf.display();
					if(cf.getExtendedState() == JFrame.ICONIFIED)
					{
						cf.setExtendedState(JFrame.NORMAL);
					}
					break;

				case "CR_LoadList":
					ResultUtilsBO.getResultUtilsInstance(null).readCGR();
					break;

				case "CR_SaveList":
					ResultUtilsBO.getResultUtilsInstance(null).writeCGR();
					break;

				case "CR_ClearTree":
					Project p = ResultUtilsBO.getResultUtilsInstance(null).getProject();
					p.clearMTSList();
					p.clearDTSList();
					DtsTreePanel dtp = GuiUtils.getCLGPanel().getDtsTreePanel();
					DtsTreeModel dtm = DtsTreePanel.getCurrentModel();
					DtsTreeModel.clearVectors();
					dtm.createTreeFromPrj(null, null, "");
					GuiUtils.getCLGPanel().repaint();
					break;

				// From Quick Results and External PDF

				case "AC_PresetClear":
					clearQRCheckBoxes("presets");
					break;
				case "AC_ShortageClear":
					clearQRCheckBoxes("shortage");
					break;
				case "AC_SJRClear":
					clearQRCheckBoxes("SJR Results");
					break;
				case "AC_WMAClear":
					clearQRCheckBoxes("WMA");
					break;
				case "AC_DShortClear":
					clearQRCheckBoxes("DShort");
					break;
				case "AC_DfcClear":
					clearQRCheckBoxes("delta_flow_criteria");
					break;
				case "AC_GenReport":
					generateReport();
					break;
				case "Rep_LoadList":
					ResultUtilsBO.getResultUtilsInstance(null).readCGR();
					break;
				case "Rep_DispCur":
					if(lstScenarios.getModel().getSize() == 0)
					{
						_dialogSvc.getOK("Error - No scenarios loaded", JOptionPane.ERROR_MESSAGE);
					}
					else if(_lstReports.getSelectedValue() == null)
					{
						_dialogSvc.getOK("Error - No display group selected", JOptionPane.ERROR_MESSAGE);
					}
					else
					{

						List<RBListItemBO> scenarios = new ArrayList<>();
						model = lstScenarios.getModel();
						for(int i = 0; i < model.getSize(); i++)
						{
							scenarios.add(model.getElementAt(i));
						}
						DisplayFrame.showDisplayFrames(
								(String) ((JList) _swingEngine.find("lstReports")).getSelectedValue(),
								scenarios);
					}
					break;
				case "Time_SELECT":

					break;
			}
		}
		catch(HeadlessException e)
		{
			LOG.error(e.getMessage());
			String messageText = "Unable to initialize action listeners.";
			_errorHandlingSvc.businessErrorHandler(messageText, (JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME),
					e);
		}
	}

	/**
	 * This method is used for the "load Scenario" button on the "Run Settings"
	 * tab.
	 *
	 * @param fileName The Name of the file.
	 */
	public void loadScenarioButton(String fileName)
	{
		try
		{
			LOG.debug("loading this cls file " + fileName);
			fileName = FilenameUtils.removeExtension(fileName);
			this._verifyControlsDele.verifyTheDataBeforeUI(Constant.SCENARIOS_DIR + fileName + Constant.CLS_EXT);
			this._scenarioSvc.applyClsFile(Constant.SCENARIOS_DIR + fileName + Constant.CLS_EXT, _swingEngine,
					_seedDataSvc.getTableIdMap());
			((JTextField) _swingEngine.find("run_txfScen")).setText(fileName + Constant.CLS_EXT);
			((JTextField) _swingEngine.find("run_txfoDSS")).setText(fileName + Constant.DV_NAME + Constant.DSS_EXT);
			_applyDynamicConDele.changeSVInitFilesAndTableInOperations(true);
			String[] c1 = new String[0];
			Object[][] data = new Object[0][0];
			((JTable) this._swingEngine.find("tblOpValues")).setModel(new DataTableModel("", c1, data, false));
			_applyDynamicConDele.applyDynamicControlForListFromFile();
			_allButtonsDele.decisionSVInitFilesAndTableInOperations();
			_auditSvc.clearAudit();
		}
		catch(Exception e)
		{
			LOG.error(e.getMessage());
			String messageText = "Unable to load scenarios.";
			_errorHandlingSvc.businessErrorHandler(messageText, (JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME),
					e);
		}
	}

	/**
	 * This method is used to display the "View Scenario Settings" button on the
	 * "Run Settings" tab.
	 */
	public void loadViewScen()
	{
		boolean pro = this._allButtonsDele.saveForViewScen();
		if(pro)
		{
			List<DataTableModel> dtmList = _scenarioDele.getScenarioTableData(null);
			ScenarioFrame scenarioFrame = new ScenarioFrame(dtmList);
			scenarioFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
			scenarioFrame.setVisible(true);
			try
			{
				Files.delete(Paths.get(Constant.SCENARIOS_DIR + Constant.CURRENT_SCENARIO + Constant.CLS_EXT));
			}
			catch(IOException ex)
			{
				// LOG.debug(ex);
				LOG.error(ex.getMessage());
				String messageText = "Unable to load scenarios.";
				_errorHandlingSvc.businessErrorHandler(messageText,
						(JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME),
						ex);
			}
		}
	}

	/**
	 * This method is used to run single batch program.
	 */
	public void runSingleBatch()
	{
		try
		{
			String clsFileName = ((JTextField) _swingEngine.find("run_txfScen")).getText();
			clsFileName = FilenameUtils.removeExtension(clsFileName);
			if(decisionBeforeTheBatchRun())
			{
				ProgressFrame progressFrame = ProgressFrame.getProgressFrameInstance();
				List<String> fileName = Arrays.asList(clsFileName);
				progressFrame.addScenarioNamesAndAction(clsFileName, Constant.BATCH_RUN);
				progressFrame.setBtnText(Constant.STATUS_BTN_TEXT_STOP);
				progressFrame.makeDialogVisible();
				_modelRunSvc.doBatch(fileName, _swingEngine, false);
			}
		}
		catch(Exception e)
		{
			LOG.error(e.getMessage());
			String messageText = "Unable to run batch file.";
			_errorHandlingSvc.businessErrorHandler(messageText, (JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME),
					e);
		}
	}

	/**
	 * This method is used to run batch program for wsidi.
	 */
	public void runSingleBatchForWsiDi()
	{
		try
		{
			String clsFileName = ((JTextField) _swingEngine.find("run_txfScen")).getText();
			clsFileName = FilenameUtils.removeExtension(clsFileName);
			if(decisionBeforeTheBatchRun())
			{
				ProgressFrame progressFrame = ProgressFrame.getProgressFrameInstance();
				List<String> fileName = Arrays.asList(clsFileName);
				progressFrame.addScenarioNamesAndAction(clsFileName, Constant.BATCH_RUN_WSIDI);
				progressFrame.setBtnText(Constant.STATUS_BTN_TEXT_STOP);
				progressFrame.makeDialogVisible();
				_modelRunSvc.doBatch(fileName, _swingEngine, true);
			}
		}
		catch(Exception e)
		{
			LOG.error(e.getMessage());
			String messageText = "Unable to run wsidi.";
			_errorHandlingSvc.businessErrorHandler(messageText, (JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME),
					e);
		}
	}

	/**
	 * This will ask the user whether to save and run the batch or run without
	 * saving or Cancel.
	 *
	 * @return Will return true if the user wants to run the batch program.
	 */
	public boolean decisionBeforeTheBatchRun()
	{
		boolean isSaved;
		try
		{
			String clsFileName = FilenameUtils
					.removeExtension(((JTextField) _swingEngine.find("run_txfScen")).getText());
			if(clsFileName.toUpperCase().equals(Constant.DEFAULT))
			{
				// JOptionPane.showMessageDialog(swingEngine.find(Constant.MAIN_FRAME_NAME),
				// "The CalLite GUI is not allowed to modify the default
				// scenario 'DEFAULT.CLS'. Please use Save As to save to a
				// different scenario file.");
				//
				// ImageIcon icon = new
				// ImageIcon(getClass().getResource("/images/CalLiteIcon.png"));
				// Object[] options = { "OK" };
				// JOptionPane optionPane = new JOptionPane(
				// "The CalLite GUI is not allowed to modify the default
				// scenario 'DEFAULT.CLS'. Please use Save As to save to a
				// different scenario file.",
				// JOptionPane.ERROR_MESSAGE, JOptionPane.OK_OPTION, null,
				// options, options[0]);
				// JDialog dialog =
				// optionPane.createDialog(swingEngine.find(Constant.MAIN_FRAME_NAME),
				// "CalLite");
				// dialog.setIconImage(icon.getImage());
				// dialog.setResizable(false);
				// dialog.setVisible(true);
				_dialogSvc.getOK(
						"Error - The CalLite GUI is not allowed to modify the default scenario 'DEFAULT.CLS'. Please use Save As to save to a different scenario file",
						JOptionPane.ERROR_MESSAGE);

				return false;
			}
			if(!Files.isExecutable(Paths.get(Constant.RUN_DETAILS_DIR + clsFileName)))
			{
				// ImageIcon icon = new
				// ImageIcon(getClass().getResource("/images/CalLiteIcon.png"));
				// Object[] options = { "Yes", "No" };
				// JOptionPane optionPane = new JOptionPane(
				// "The cls file does not have a corresponding directory
				// structure.\nThe batch will not run without this.\nDo you want
				// to save to create that directory?",
				// JOptionPane.QUESTION_MESSAGE, JOptionPane.OK_CANCEL_OPTION,
				// null, options, options[0]);
				// JDialog dialog =
				// optionPane.createDialog(swingEngine.find(Constant.MAIN_FRAME_NAME),
				// "CalLite");
				// dialog.setIconImage(icon.getImage());
				// dialog.setResizable(false);
				// dialog.setVisible(true);
				String option = _dialogSvc.getYesNo(
						"The cls file does not have a corresponding directory structure.\nThe batch will not run without this.\nDo you want to save to create that directory?",
						JOptionPane.QUESTION_MESSAGE);
				switch(option)
				{
					case "Yes":
						return this._allButtonsDele.saveCurrentStateToFile(clsFileName);
					case "No":
						return false;
				}
			}
			isSaved = false;
			if(_auditSvc.hasValues())
			{

				// ImageIcon icon = new
				// ImageIcon(getClass().getResource("/images/CalLiteIcon.png"));
				// Object[] options = { "Yes", "No" };
				// JOptionPane optionPane = new JOptionPane(
				// "Scenario selections have changed. Would you like to save the
				// changes?",
				// JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION,
				// null, options, options[1]);
				// JDialog dialog =
				// optionPane.createDialog(swingEngine.find(Constant.MAIN_FRAME_NAME),
				// "CalLite");
				// dialog.setIconImage(icon.getImage());
				// dialog.setResizable(false);
				// dialog.setVisible(true);
				String option = _dialogSvc.getYesNo(
						"Scenario selections have changed. Would you like to save the changes?",
						JOptionPane.QUESTION_MESSAGE);
				switch(option)
				{
					case "Yes":
						isSaved = this._allButtonsDele.saveCurrentStateToFile(clsFileName);
						break;
					case "No":
						loadScenarioButton(((JTextField) _swingEngine.find("run_txfScen")).getText());
						isSaved = true;
						break;
				}

			}
			else
			{
				isSaved = true;
			}
			return isSaved;
		}
		catch(HeadlessException e)
		{
			LOG.error(e.getMessage());
			String messageText = "Unable to run batch file.";
			_errorHandlingSvc.businessErrorHandler(messageText, (JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME),
					e);
		}
		return false;
	}

	/**
	 * Clears Quick Result checkboxes that are on panel named "panelName"
	 *
	 * @param panelName
	 */
	private void clearQRCheckBoxes(String panelName)
	{
		JPanel panel = (JPanel) _swingEngine.find(panelName);
		Component[] components = panel.getComponents();
		for(int i = 0; i < components.length; i++)
		{
			if(components[i] instanceof JCheckBox)
			{
				JCheckBox c = (JCheckBox) components[i];
				c.setSelected(false);
			}
		}
	}

	/**
	 * Generates PDF report from "External PDF" dashboard - action "ACGenReport"
	 */
	private void generateReport()
	{
		if(((JTextField) _swingEngine.find("tfReportFILE1")).getText().isEmpty()
				|| ((JTextField) _swingEngine.find("tfReportFILE2")).getText().isEmpty()
				|| ((JTextField) _swingEngine.find("tfReportFILE3")).getText().isEmpty())
		{
			_dialogSvc.getOK("You must specify the source DSS files and the output PDF file",
					JOptionPane.ERROR_MESSAGE);
		}
		else
		{
			try(FileInputStream fin = new FileInputStream(
					((JTextField) _swingEngine.find("tfTemplateFILE")).getToolTipText());
				BufferedReader br = new BufferedReader(new InputStreamReader(fin)))
			{

				// Create an inputstream from template file;
				// Open the template file
				String theText = br.readLine() + "\n";
				theText = theText + br.readLine() + "\n";
				theText = theText + br.readLine() + "\n";
				String skipLine = br.readLine();
				theText = theText + "FILE_BASE\t" + ((JTextField) _swingEngine.find("tfReportFILE1")).getToolTipText()
						+ "\n";
				skipLine = br.readLine();
				theText = theText + "NAME_BASE\t\"" + ((JTextField) _swingEngine.find("tfReportNAME1")).getText()
						+ "\"\n";
				skipLine = br.readLine();
				theText = theText + "FILE_ALT\t" + ((JTextField) _swingEngine.find("tfReportFILE2")).getToolTipText()
						+ "\n";
				skipLine = br.readLine();
				theText = theText + "NAME_ALT\t\"" + ((JTextField) _swingEngine.find("tfReportNAME2")).getText()
						+ "\"\n";
				skipLine = br.readLine();
				theText = theText + "OUTFILE\t" + ((JTextField) _swingEngine.find("tfReportFILE3")).getToolTipText()
						+ "\n";
				skipLine = br.readLine();
				theText = theText + "NOTE\t\"" + ((JTextArea) _swingEngine.find("taReportNOTES")).getText() + "\"\n";
				skipLine = br.readLine();
				theText = theText + "ASSUMPTIONS\t\"" + ((JTextArea) _swingEngine.find("taReportASSUMPTIONS")).getText()
						+ "\"\n";
				skipLine = br.readLine();
				theText = theText + "MODELER\t\"" + ((JTextField) _swingEngine.find("tfReportMODELER")).getText()
						+ "\"\n";

				theText = theText + "TABLE_FONT_SIZE\t" + ((JTextField) _swingEngine.find("tfFontSize")).getText()
						+ "\n";

				String aLine = br.readLine();
				while(aLine != null)
				{
					theText = theText + aLine + "\n";
					aLine = br.readLine();
				}
				theText = theText + "\n";
				ByteArrayInputStream bs = new ByteArrayInputStream(theText.getBytes());
				try
				{
					Report report = new Report(bs, ((JTextField) _swingEngine.find("tfReportFILE3")).getToolTipText());
					report.execute();
				}
				catch(IOException e1)
				{
					// LOG.debug(e1.getMessage()); // Not sure - should catch
					// // thread problems like
					// // already-open PDF?
					LOG.error(e1.getMessage());
					String messageText = "Unable to display report.";
					_errorHandlingSvc.businessErrorHandler(messageText,
							(JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME), e1);
				}
			}
			catch(IOException e1)
			{
				LOG.error(e1.getMessage());
				String messageText = "Unable to display report.";
				_errorHandlingSvc.businessErrorHandler(messageText,
						(JFrame) _swingEngine.find(Constant.MAIN_FRAME_NAME),
						e1);
				// (?)
			}
		}
	}
}
