/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vista_db_dss_DSSDataReader */

#ifndef _Included_vista_db_dss_DSSDataReader
#define _Included_vista_db_dss_DSSDataReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vista_db_dss_DSSDataReader
 * Method:    generateCatalog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vista_db_dss_DSSDataReader_generateCatalog
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vista_db_dss_DSSDataReader
 * Method:    getRecordType
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_vista_db_dss_DSSDataReader_getRecordType
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vista_db_dss_DSSDataReader
 * Method:    retrieveRegularTimeSeries
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJZLvista/db/dss/DSSData;)I
 */
JNIEXPORT jint JNICALL Java_vista_db_dss_DSSDataReader_retrieveRegularTimeSeries
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jboolean, jobject);

/*
 * Class:     vista_db_dss_DSSDataReader
 * Method:    retrieveIrregularTimeSeries
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJZLvista/db/dss/DSSData;)I
 */
JNIEXPORT jint JNICALL Java_vista_db_dss_DSSDataReader_retrieveIrregularTimeSeries
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jboolean, jobject);

/*
 * Class:     vista_db_dss_DSSDataReader
 * Method:    retrievePairedData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lvista/db/dss/DSSData;)I
 */
JNIEXPORT jint JNICALL Java_vista_db_dss_DSSDataReader_retrievePairedData
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
