/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vista_db_dss_DSSDataWriter */

#ifndef _Included_vista_db_dss_DSSDataWriter
#define _Included_vista_db_dss_DSSDataWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vista_db_dss_DSSDataWriter
 * Method:    storeTimeSeriesData
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJLvista/db/dss/DSSData;Z)V
 */
JNIEXPORT void JNICALL Java_vista_db_dss_DSSDataWriter_storeTimeSeriesData
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jobject, jboolean);

/*
 * Class:     vista_db_dss_DSSDataWriter
 * Method:    storeIrregularTimeSeriesData
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJLvista/db/dss/DSSData;Z)V
 */
JNIEXPORT void JNICALL Java_vista_db_dss_DSSDataWriter_storeIrregularTimeSeriesData
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jobject, jboolean);

/*
 * Class:     vista_db_dss_DSSDataWriter
 * Method:    storePairedData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lvista/db/dss/DSSData;Z)V
 */
JNIEXPORT void JNICALL Java_vista_db_dss_DSSDataWriter_storePairedData
  (JNIEnv *, jobject, jstring, jstring, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
