# Makefile to update the catalogs for dss files
# get all files under current directory
PACKAGE=calsim.schematic

JAVA_FILES = LabeledSymbol.java LabeledLine.java CalsimSchematic.java CalsimSchematicDataModel.java CalsimSymbolData.java CalsimSchematicFrame.java CalsimSchematicCanvas.java RequestHandler.java PopupMenuHandler.java DragHandler.java NetworkSchematicData.java AddNodeHandler.java AddArcHandler.java RemoveNodeHandler.java RemoveArcHandler.java SchematicEditor.java 

PACKAGE_LOC=calsim/schematic

# local first then common
include ../local.makefile
include ../common.makefile
