/*
 * Enhanced Post Processing Tool (EPPT) Copyright (c) 2019.
 *
 * EPPT is copyrighted by the State of California, Department of Water Resources. It is licensed
 * under the GNU General Public License, version 2. This means it can be
 * copied, distributed, and modified freely, but you may not restrict others
 * in their ability to copy, distribute, and modify it. See the license below
 * for more details.
 *
 * GNU General Public License
 */

/* Generated By:JavaCC: Do not edit this line. WreslParserConstants.java */
package calsim.wreslcoder.wresl;

public interface WreslParserConstants
{

	int EOF = 0;
	int SL_COMMENT = 5;
	int ML_COMMENT = 6;
	int LHS = 7;
	int RHS = 8;
	int LESSTHAN = 9;
	int GRTRTHAN = 10;
	int UNBOUNDED = 11;
	int PENALTY = 12;
	int CONSTRAIN = 13;
	int SEQUENCE = 14;
	int MODEL = 15;
	int ORDER = 16;
	int INCLUDE = 17;
	int VALUE = 18;
	int KIND = 19;
	int UNITS = 20;
	int CONVERT = 21;
	int ALIAS = 22;
	int SELECT = 23;
	int WHERE = 24;
	int DESC = 25;
	int HEADER = 26;
	int TIMESERIES = 27;
	int FROM = 28;
	int MAXIMUM = 29;
	int MINIMUM = 30;
	int MEAN = 31;
	int LINEAR = 32;
	int UNKNOWN = 33;
	int USE = 34;
	int GIVEN = 35;
	int RESULT = 36;
	int STD = 37;
	int ALWAYS = 38;
	int GOAL = 39;
	int GOALSET = 40;
	int DEFINE = 41;
	int CONDITION = 42;
	int SUM = 43;
	int EXTERNAL = 44;
	int CASE = 45;
	int LOWER = 46;
	int UPPER = 47;
	int INTEGER = 48;
	int ADD = 49;
	int SUBTRACT = 50;
	int MULTIPLY = 51;
	int DIVIDE = 52;
	int AND = 53;
	int OR = 54;
	int NOT = 55;
	int GT = 56;
	int LT = 57;
	int SINGLE_EQ = 58;
	int GE = 59;
	int LE = 60;
	int EQ = 61;
	int NE = 62;
	int OBJECTIVE = 63;
	int ABS = 64;
	int INT = 65;
	int NINT = 66;
	int REAL = 67;
	int MOD = 68;
	int EXP = 69;
	int LOG = 70;
	int LOG10 = 71;
	int SQRT = 72;
	int MAX = 73;
	int MIN = 74;
	int POW = 75;
	int RANGE = 76;
	int DATE = 77;
	int ARRAY = 78;
	int FILLARRAY = 79;
	int LOCAL = 80;
	int GLOBAL = 81;
	int DAYMONTH = 82;
	int MONTHYEAR = 83;
	int DAYMONTHYEAR = 84;
	int DAY = 85;
	int MONTH = 86;
	int YEAR = 87;
	int CONSTANT = 88;
	int DOUBLE = 89;
	int DIGIT = 90;
	int ID = 91;
	int TIME_UNIT = 92;
	int IDENTIFIER = 93;
	int LETTER = 94;
	int QUOTED_LITERAL = 95;
	int DLL = 96;

	int DEFAULT = 0;


}
