CALSIM_HOME = D:/wrims1.3/wrims1/calsim
JAVA_HOME = d:/jdk/jdk1.6.0_20
DELETE = rm -rf #del
CMD_SEP = ; #&
PATH_SEP = /
CPATH_SEP=;
JAVACC=D:/wrims1.3/3rd_party/javacc2.0/bin/javacc.bat
JAVACC_OPTIONS=
MAKE=D:/wrims1.3/3rd_party/cygnus/bin/make.exe --unix
JAR = $(JAVA_HOME)${PATH_SEP}bin${PATH_SEP}jar.exe
WEBSTART_LIB=D:/wrims1.3/3rd_party/WebstartSDK3.0/classes
