<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Enhanced Post Processing Tool (EPPT) Copyright (c) 2019.
  ~
  ~ EPPT is copyrighted by the State of California, Department of Water Resources. It is licensed
  ~ under the GNU General Public License, version 2. This means it can be
  ~ copied, distributed, and modified freely, but you may not restrict others
  ~ in their ability to copy, distribute, and modify it. See the license below
  ~ for more details.
  ~
  ~ GNU General Public License
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>gov.ca.water</groupId>
	<artifactId>eppt-parent</artifactId>
	<version>1.2.2-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>EPPT Parent</name>

	<modules>
		<module>../branding</module>
		<module>../application</module>
		<module>../eppt-nbui</module>
		<module>../eppt-core</module>
		<module>../eppt-ui</module>
		<module>../eppt-scenario</module>
		<module>../eppt-calsim-gui</module>
		<module>../eppt-vista</module>
        <module>../eppt-report-engine</module>
		<module>../eppt-jasper-engine</module>
		<module>../eppt-plots</module>
		<module>../eppt-trend-reporting</module>
	</modules>

	<scm>
		<developerConnection>scm:git:https://github.com/CalSimCalLite/DWR-Enhanced-Post-Processing-Tool.git</developerConnection>
	</scm>
	<properties>
		<netbeans.version>RELEASE300</netbeans.version>
		<monolith.version>5.3.5</monolith.version>
		<rmajavafx.version>3.0.1</rmajavafx.version>
		<javafx.version>23</javafx.version>
		<nbm.maven.plugin.version>14.3</nbm.maven.plugin.version>
		<javaheclib.version>7-IA-win-x64</javaheclib.version>


		<brandingToken>dwr_eppt</brandingToken>
		<maven.build.timestamp.format>yyyy-MM-dd-HHmmss</maven.build.timestamp.format>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.nbm.includeRuntimeModuleLibraries>true</maven.nbm.includeRuntimeModuleLibraries>
	</properties>
	<repositories>
		<repository>
			<id>github</id>
			<url>https://maven.pkg.github.com/CentralValleyModeling/DWR-Enhanced-Post-Processing-Tool/</url>
		</repository>
		<repository>
			<id>github-wrimsdeps</id>
			<url>https://maven.pkg.github.com/CentralValleyModeling/wrims-engine-dependencies/</url>
		</repository>
		<repository>
			<id>hec-maven</id>
			<url>https://www.hec.usace.army.mil/nexus/repository/maven-public/</url>
		</repository>
	</repositories>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.netbeans.utilities</groupId>
				<artifactId>nbm-maven-plugin</artifactId>
				<version>${nbm.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<brandingToken>${brandingToken}</brandingToken>
					<cluster>${brandingToken}</cluster>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.15.0</version>
				<configuration>
					<source>21</source>
					<target>21</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.netbeans.api</groupId>
							<artifactId>org-netbeans-api-annotations-common</artifactId>
							<version>${netbeans.version}</version>
						</path>
						<path>
							<groupId>org.netbeans.api</groupId>
							<artifactId>org-openide-util-lookup</artifactId>
							<version>${netbeans.version}</version>
						</path>
						<path>
							<groupId>org.netbeans.api</groupId>
							<artifactId>org-openide-windows</artifactId>
							<version>${netbeans.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.5.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.0</version>
			</plugin>
<!--			<plugin>-->
<!--				<groupId>org.apache.maven.plugins</groupId>-->
<!--				<artifactId>maven-release-plugin</artifactId>-->
<!--				<version>2.5.3</version>-->
<!--				<configuration>-->
<!--					<tagNameFormat>v@{project.version}</tagNameFormat>-->
<!--				</configuration>-->
<!--			</plugin>-->
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<!-- Replaced with lookup-compat since og lookup isn't Java 21 compatible -->
			<groupId>mil.army.usace.hec</groupId>
			<artifactId>lookup</artifactId>
			<version>2.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<!-- Compile with Netbeans Service Annotations -->
			<groupId>mil.army.usace.hec</groupId>
			<artifactId>service-annotations</artifactId>
			<version>2.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<!-- Dependency gets duplicated and angers Netbeans -->
			<groupId>javax.media</groupId>
			<artifactId>jai_imageio</artifactId>
			<version>1.1</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
