# get all files under current directory

JAVA_FILES = InputHandler.java DataSource.java DataSourceUI.java TestDataSourceUI.java InputObject.java TestInputObject.java
#
PACKAGE_LOC=calsim/schematic/input
# local first then common
include ../../local.makefile
include ../../common.makefile









