# Makefile to update the catalogs for dss files
# get all files under current directory
JAVA_FILES = MSWThread.java InitOperator.java LumpOperator.java MonToDayOperator.java MSWUtil.java MultiStudyWrapper.java MYDate.java ReferenceOperator.java StudyInterface.java StudyWrapper.java TransferOperator.java MSWGui.java
#
PACKAGE_LOC=calsim/msw

# local first then common
include ../local.makefile
include ../common.makefile

main:
