# Makefile to update the catalogs for dss files
# get all files under current directory
JAVA_FILES = Node.java Arc.java Network.java GymUtils.java ChannelArc.java StorageArc.java DemandArc.java InputArc.java ReturnArc.java GenWresl.java BoundaryNode.java
#
PACKAGE_LOC=calsim/gym

# local first then common
include ../local.makefile
include ../common.makefile

main:
